name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '17'
        cache: 'maven'
    - name: mvn test
      id: mvn-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: mvn test
        setup-command: ''
        command: mvn test
        timeout: 1
        max-score: 3
    - name: checkstyle
      id: checkstyle
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: checkstyle
        setup-command: ''
        command: mvn install
        timeout: 10
        max-score: 3
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        MVN-TEST_RESULTS: "${{steps.mvn-test.outputs.result}}"
        CHECKSTYLE_RESULTS: "${{steps.checkstyle.outputs.result}}"
      with:
        runners: mvn-test,checkstyle
